project_id = "bbfkorzehzoaogrnuyqp"

[functions.send-recovery-email]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.check-duplicate-lead]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.cleanup-analytics]
verify_jwt = false

[functions.send-lead-result-email]
verify_jwt = false

[functions.send-monthly-report]
verify_jwt = false

[functions.check-proposal-expiration]
verify_jwt = false